-- MySQL Script generated by MySQL Workbench
-- Sun Mar 18 17:48:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`slider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`slider` (
  `idslider` INT NOT NULL AUTO_INCREMENT,
  `imagen_slider` VARCHAR(75) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` TEXT(500) NOT NULL,
  PRIMARY KEY (`idslider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`institucional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`institucional` (
  `idinstitucional` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `prezi` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idinstitucional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idservicios` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` TEXT(500) NOT NULL,
  `subtitulo` VARCHAR(45) NOT NULL,
  `subtexto` TEXT(500) NOT NULL,
  PRIMARY KEY (`idservicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`portfolio` (
  `idportfolio` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `separadores` VARCHAR(45) NOT NULL,
  `imagen_portfolio` VARCHAR(75) NOT NULL,
  `subtitulo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idportfolio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contactenos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactenos` (
  `idcontactenos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(320) NOT NULL,
  PRIMARY KEY (`idcontactenos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
